name: Reusable Proxmox Plan

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        default: ubuntu-latest
      working-directory:
        type: string
        required: false
        default: "."
      setup-command:
        type: string
        required: false
        default: ""
      plan-command:
        type: string
        required: true
      upload-artifact-path:
        type: string
        required: false
        default: ""
      artifact-name:
        type: string
        required: false
        default: proxmox-plan

permissions:
  contents: read

jobs:
  proxmox-plan:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: cobycloud/actions/actions/proxmox-command@main
        with:
          working-directory: ${{ inputs.working-directory }}
          setup-command: ${{ inputs.setup-command }}
          command: ${{ inputs.plan-command }}
          upload-artifact-path: ${{ inputs.upload-artifact-path }}
          artifact-name: ${{ inputs.artifact-name }}
