name: Reusable RPM Publish

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        default: ubuntu-latest
      working-directory:
        type: string
        required: false
        default: "."
      setup-command:
        type: string
        required: false
        default: ""
      publish-command:
        type: string
        required: true
      package-path:
        type: string
        required: false
        default: "*.rpm"

permissions:
  contents: read

jobs:
  rpm-publish:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4

      - uses: cobycloud/actions/actions/rpm-publish@main
        with:
          working-directory: ${{ inputs.working-directory }}
          setup-command: ${{ inputs.setup-command }}
          publish-command: ${{ inputs.publish-command }}
          package-path: ${{ inputs.package-path }}
