name: Reusable crates.io Publish

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        default: ubuntu-latest
      publish-mode:
        type: string
        required: false
        default: token
      rust-toolchain:
        type: string
        required: false
        default: stable
      working-directory:
        type: string
        required: false
        default: "."
      registry:
        type: string
        required: false
        default: ""
      package:
        type: string
        required: false
        default: ""
      features:
        type: string
        required: false
        default: ""
      all-features:
        type: boolean
        required: false
        default: false
      no-default-features:
        type: boolean
        required: false
        default: false
      dry-run:
        type: boolean
        required: false
        default: false
      allow-dirty:
        type: boolean
        required: false
        default: false
      no-verify:
        type: boolean
        required: false
        default: false
      skip-existing:
        type: boolean
        required: false
        default: false
    secrets:
      CRATES_API_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  publish:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v5

      - uses: cobycloud/actions/actions/crates-publish@main
        with:
          publish-mode: ${{ inputs.publish-mode }}
          rust-toolchain: ${{ inputs.rust-toolchain }}
          working-directory: ${{ inputs.working-directory }}
          crates-api-token: ${{ secrets.CRATES_API_TOKEN }}
          registry: ${{ inputs.registry }}
          package: ${{ inputs.package }}
          features: ${{ inputs.features }}
          all-features: ${{ inputs.all-features }}
          no-default-features: ${{ inputs.no-default-features }}
          dry-run: ${{ inputs.dry-run }}
          allow-dirty: ${{ inputs.allow-dirty }}
          no-verify: ${{ inputs.no-verify }}
          skip-existing: ${{ inputs.skip-existing }}
