name: Reusable Build Windows Artifact

on:
  workflow_call:
    inputs:
      runner:
        type: string
        required: false
        default: windows-latest
      working-directory:
        type: string
        required: false
        default: "."
      setup-command:
        type: string
        required: false
        default: ""
      build-command:
        type: string
        required: true
      windows-build-command:
        type: string
        required: false
        default: ""
      artifact-path:
        type: string
        required: true
      artifact-name:
        type: string
        required: false
        default: windows-artifact

permissions:
  contents: read

jobs:
  build-windows-artifact:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v5

      - uses: cobycloud/actions/actions/platform-artifact-build@main
        with:
          working-directory: ${{ inputs.working-directory }}
          setup-command: ${{ inputs.setup-command }}
          build-command: ${{ inputs.build-command }}
          windows-build-command: ${{ inputs.windows-build-command }}
          artifact-path: ${{ inputs.artifact-path }}
          artifact-name: ${{ inputs.artifact-name }}
